# -*- coding: utf-8 -*-
import folder_paths
import nodes
import json
import os

class AnyType(str):
    """A special class that is always equal in not equal comparisons."""
    def __ne__(self, __value: object) -> bool:
        return False

any_type = AnyType("*")

class LoadLoraMerge:
    """
    A universal node that merges the functionality of LoadLoraBatch and WanVideoLoraBatch.
    It can optionally take a model and apply LoRAs, and also output a WANVIDLORA-formatted list.
    The state of the LoRA widgets is saved and restored via a single 'loras_info' string input.
    """
    @classmethod
    def INPUT_TYPES(cls):
        return {
            "required": {
                "enabled": ("BOOLEAN", {"default": True}),
            },
            "optional": {
                "model": ("MODEL",),
                "prev_lora": ("WANVIDLORA",),
                "blocks": ("SELECTEDBLOCKS",),
                # This hidden widget stores the serialized state of the lora list for saving/loading.
                "loras_info": ("STRING", {"default": "[]", "multiline": False, "hidden": True}),
            },
            # Kwargs are dynamically generated by the JS for each LoRA widget and the settings widget.
            "hidden": {
                "prompt": ["PROMPT"], 
                "extra_pnginfo": ["EXTRA_PNGINFO"],
            },
        }

    RETURN_TYPES = (any_type, "WANVIDLORA",)
    RETURN_NAMES = ("model", "lora",)
    FUNCTION = "process"
    CATEGORY = "A_my_nodes/loaders"

    def process(self, enabled, model=None, prev_lora=None, blocks={}, loras_info="[]", **kwargs):
        if not enabled:
            print(f"[LoadLoraMerge] Node is disabled. Bypassing.")
            return (model, [],)

        output_model = model
        print(f"[LoadLoraMerge] model is {'✅' if model is not None else '❌'}.")
        
        # --- Get settings and loras from loras_info ---
        low_mem_load = False
        merge_loras = True
        loras_data = []

        try:
            data = json.loads(loras_info)
            # print(f"[LoadLoraMerge] data: \n{data}")
            if isinstance(data, dict):
                settings_data = data.get('settings', {})
                if isinstance(settings_data, dict):
                    low_mem_load = settings_data.get("value1", False)
                    merge_loras = settings_data.get("value2", True)
                
                loras_data = data.get('loras', [])
        except (json.JSONDecodeError, TypeError):
            print(f"[LoadLoraMerge] Failed to parse loras_info, it might be empty or invalid JSON. Value: {loras_info}")

        if not merge_loras:
            low_mem_load = False
            
        print(f"[LoadLoraMerge] Settings: low_mem_load={'✅' if low_mem_load else '❌'}, merge_loras={'✅' if merge_loras else '❌'}")
            
        # --- Process LoRAs ---
        loras_list_for_wan = list(prev_lora) if prev_lora else []
        use_lora_num = 0
        for value in loras_data:
            if not isinstance(value, dict):
                continue

            enabled = value.get("on", True)
            lora_name = value.get("lora", "None")
            strength = value.get("strength", 1.0)
            
            if (not enabled) or (lora_name in ("none", "None", "", None)) or (strength == 0.0):
                continue

            print(f"[LoadLoraMerge] 🛰️Enabled LoRA: {lora_name}, Strength: {strength}")
            use_lora_num += 1

            # --- Part 1: Apply LoRA to model (if model is provided) ---
            if output_model is not None:
                try:
                    output_model, _ = nodes.LoraLoader().load_lora(output_model, None, lora_name, strength, 0)
                    # print(f"[LoadLoraMerge] 💡Applied LoRA to model: {lora_name}")
                except Exception as e:
                    print(f"[LoadLoraMerge] ❌ Failed to apply LoRA to model: {lora_name}, {e}")
                    # Continue to next LoRA even if one fails
                    continue

            # --- Part 2: Collect LoRA for WANVIDLORA output ---
            try:
                lora_path = folder_paths.get_full_path_or_raise("loras", lora_name)
                loras_list_for_wan.append({
                    "path": lora_path,
                    "strength": round(strength, 4) if not isinstance(strength, list) else strength,
                    "name": os.path.splitext(lora_name)[0],
                    "blocks": blocks.get("selected_blocks", {}) if blocks else {},
                    "layer_filter": blocks.get("layer_filter", "") if blocks else "",
                    "low_mem_load": low_mem_load,
                    "merge_loras": merge_loras,
                })
                # print(f"[LoadLoraMerge] 💡Collected LoRA for WanVideo: {lora_name}")
            except Exception as e:
                print(f"[LoadLoraMerge] ❌ Failed to find LoRA path for WanVideo part: {lora_name}, {e}")

        # If no model was input, the first output will be None.
        print(f"[LoadLoraMerge] 🛰️Use LoRA num: {use_lora_num}")
        return (output_model, loras_list_for_wan,)